### ISSUE TITLE
ETH

### ISSUE THREAD

**Issue by RasyidMMJ** [RasyidMMJ/ETH#2]
CAN"T NOT TRANSACTION TRUSTWALLET "SEND", "RECEIVE", "BUY", "SELL"
ETH "107.789504" ADDRESS "0x84811d901063391658ddaCb6Dbc6926d9014038D"

**Comment by UserGithub005** [comment]
Hallo RasyidMMJ,,,,
Please update your address wallet.

~Refactored space waddle

**Comment by RasyidMMJ** [comment]
0x26988c5054ff1e2c37cf0874963c7da23f4415e8

MY update your address wallet.

**Comment by UserGithub005** [comment]
Link address wallet 0x26988c5054ff1e2c37cf0874963c7da23f4415e8


~Refactored space waddle

**Comment by UserGithub005** [comment]
@RasyidMMJ Please send a link to your wallet address from the Big Exchange Onchain network, I'll wait today or the process will be cancelled. Please respond


~~Refactored space waddle
